//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASN_API_MASTER
    {
        public int ID { get; set; }
        public string AUTH_URL { get; set; }
        public string ASN_URL { get; set; }
        public string Customer_Code { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public string client_id { get; set; }
        public string grant_type { get; set; }
        public string client_secret { get; set; }
    }
}
