//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalSignDetail
    {
        public int DSDetailsId { get; set; }
        public Nullable<int> ClientLineId { get; set; }
        public string ClientId { get; set; }
        public string KeyName { get; set; }
        public string KeyPinNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
