//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSMaster
    {
        public int DSMasterId { get; set; }
        public string KeyName { get; set; }
        public string KeyPinNo { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SignName { get; set; }
        public string IssuerName { get; set; }
        public string SerialNo { get; set; }
        public string ThumbPrint { get; set; }
        public string CertificateName { get; set; }
        public string STATUS { get; set; }
        public string ContainerName { get; set; }
        public string ProviderName { get; set; }
        public Nullable<System.DateTime> ValidityBefore { get; set; }
        public Nullable<System.DateTime> ValidityAfter { get; set; }
    }
}
