//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DSMdbEntities : DbContext
    {
        public DSMdbEntities()
            : base("name=DSMdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASN_API_MASTER> ASN_API_MASTER { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<DigitalSignDetail> DigitalSignDetails { get; set; }
        public virtual DbSet<DSMaster> DSMasters { get; set; }
        public virtual DbSet<EDIConfiguration> EDIConfigurations { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<PART_MASTER> PART_MASTER { get; set; }
        public virtual DbSet<Quarantine> Quarantines { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Setup> Setups { get; set; }
        public virtual DbSet<TemplateMaster> TemplateMasters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LICENCE> LICENCES { get; set; }
        public virtual DbSet<Server_trigger> Server_trigger { get; set; }
        public virtual DbSet<TEMP_AUTH_TOKEN> TEMP_AUTH_TOKEN { get; set; }
    
        public virtual ObjectResult<SP_FILTER_INVOICE_Result> SP_FILTER_INVOICE(string invNumber, string fromDate, string toDate)
        {
            var invNumberParameter = invNumber != null ?
                new ObjectParameter("InvNumber", invNumber) :
                new ObjectParameter("InvNumber", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FILTER_INVOICE_Result>("SP_FILTER_INVOICE", invNumberParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GET_INVOICE_Result> SP_GET_INVOICE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_INVOICE_Result>("SP_GET_INVOICE");
        }
    
        public virtual ObjectResult<sp_search_Invoice_Result> sp_search_Invoice(string invoiceNo, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_search_Invoice_Result>("sp_search_Invoice", invoiceNoParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SP_GET_SYSINVOICE_Result> SP_GET_SYSINVOICE(string systemName)
        {
            var systemNameParameter = systemName != null ?
                new ObjectParameter("SystemName", systemName) :
                new ObjectParameter("SystemName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SYSINVOICE_Result>("SP_GET_SYSINVOICE", systemNameParameter);
        }
    
        public virtual ObjectResult<SP_GET_SEARCHINVOICE_Result> SP_GET_SEARCHINVOICE(string invoiceNo)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SEARCHINVOICE_Result>("SP_GET_SEARCHINVOICE", invoiceNoParameter);
        }
    
        public virtual ObjectResult<SP_GET_QUARNINVOICE_Result> SP_GET_QUARNINVOICE(string invoiceNo)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_QUARNINVOICE_Result>("SP_GET_QUARNINVOICE", invoiceNoParameter);
        }
    
        public virtual ObjectResult<SP_Invoices_Result> SP_Invoices(string invoiceNo)
        {
            var invoiceNoParameter = invoiceNo != null ?
                new ObjectParameter("InvoiceNo", invoiceNo) :
                new ObjectParameter("InvoiceNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Invoices_Result>("SP_Invoices", invoiceNoParameter);
        }
    
        public virtual ObjectResult<SP_Quarantine_Result> SP_Quarantine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Quarantine_Result>("SP_Quarantine");
        }
    }
}
