//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIConfiguration
    {
        public int EdiId { get; set; }
        public Nullable<int> ClientLineId { get; set; }
        public string ClientId { get; set; }
        public Nullable<bool> IsEdi { get; set; }
        public string EdiLink { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string FromEmail { get; set; }
        public string FromPwd { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
