//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public string CustomerName { get; set; }
        public string VehicleNumber { get; set; }
        public string VendorCode { get; set; }
        public string ShopCode { get; set; }
        public string PONumber { get; set; }
        public string PartNumber { get; set; }
        public string InvNumber { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string InvQuantity { get; set; }
        public string InvValue { get; set; }
        public string TarrifNumber { get; set; }
        public string BedAmount { get; set; }
        public string SGST { get; set; }
        public string IGST { get; set; }
        public string VatAmount { get; set; }
        public string UnitPrice { get; set; }
        public string MaterialCost { get; set; }
        public string CGST { get; set; }
        public string ConsigneePartCost { get; set; }
        public string ExciseDutyCost { get; set; }
        public string AssessableValue { get; set; }
        public string CSTAmount { get; set; }
        public string ToolCost { get; set; }
        public string ConsigneeMatlCost { get; set; }
        public string GSTN { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DSStatus { get; set; }
        public byte[] OriginalPDF { get; set; }
        public byte[] DuplicatePDF { get; set; }
        public byte[] QuadraplicatePDF { get; set; }
        public byte[] ExtraPDF { get; set; }
        public string PrintStatus { get; set; }
        public string APIStatus { get; set; }
        public string APIMessage { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
        public Nullable<int> Finyear { get; set; }
        public string SystemName { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string GateNo { get; set; }
        public string ContentType { get; set; }
        public string UOM { get; set; }
        public string CGSTrate { get; set; }
        public string SGSTrate { get; set; }
        public string IGSTrate { get; set; }
        public string TotalAmnt { get; set; }
        public string TotalGSTvalue { get; set; }
        public string TotalAmntwords { get; set; }
        public string TotalGSTvaluewords { get; set; }
        public string BillToCustomer { get; set; }
        public string BTaddress { get; set; }
        public string BTstate { get; set; }
        public string BTstatecode { get; set; }
        public string BTgst { get; set; }
        public string BTpan { get; set; }
        public string ShipToCustomer { get; set; }
        public string STaddress { get; set; }
        public string STstate1 { get; set; }
        public string STstatecode1 { get; set; }
        public string STgst1 { get; set; }
        public string STpan1 { get; set; }
        public string RR_GR { get; set; }
        public string Destination { get; set; }
        public string Currency { get; set; }
        public string Ewaybill_no { get; set; }
        public string Carrier { get; set; }
        public string PDF_Generation { get; set; }
        public string Case_no { get; set; }
        public string Qty_in_case { get; set; }
        public string TCS { get; set; }
        public string Lot_Code { get; set; }
        public string E_InvNo { get; set; }
        public Nullable<System.DateTime> Manfac_Date { get; set; }
        public string EXTRA_NUM_1 { get; set; }
        public string EXTRA_NUM_2 { get; set; }
        public string EXTRA_NUM_3 { get; set; }
        public string EXTRA_NUM_4 { get; set; }
        public string EXTRA_NUM_5 { get; set; }
        public string EXTRA_NUM_6 { get; set; }
        public string EXTRA_NUM_7 { get; set; }
        public string EXTRA_CHAR_1 { get; set; }
        public string EXTRA_CHAR_2 { get; set; }
        public string EXTRA_CHAR_3 { get; set; }
        public string EXTRA_CHAR_4 { get; set; }
        public string EXTRA_CHAR_5 { get; set; }
        public Nullable<System.DateTime> Date_1 { get; set; }
        public Nullable<System.DateTime> Date_2 { get; set; }
        public Nullable<System.DateTime> Date_3 { get; set; }
        public Nullable<System.DateTime> Date_4 { get; set; }
        public Nullable<System.DateTime> Date_5 { get; set; }
        public string ASN_NUMBER { get; set; }
    }
}
