//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENCE
    {
        public int ID { get; set; }
        public string LICENCE_ID { get; set; }
        public System.DateTime DATE_PURCHASED { get; set; }
        public string SYSTEM_NAME { get; set; }
    }
}
