//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PART_MASTER
    {
        public int ID { get; set; }
        public string PART_NAME { get; set; }
        public string PART_ID { get; set; }
        public string PART_NO { get; set; }
        public string COIL_NO { get; set; }
        public string SPECIFICATION { get; set; }
        public string BASIC { get; set; }
        public string FREIGHT { get; set; }
        public string AMORTISATION { get; set; }
        public string UOM { get; set; }
        public string GATE_NO { get; set; }
        public string CHAPTER_HEADING { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTAINER { get; set; }
        public string STUFF_QTY { get; set; }
        public string LOCATION { get; set; }
        public string SHOP { get; set; }
        public string SHOP_CODE { get; set; }
        public string STD_WEIGHT { get; set; }
        public string THICKNESS { get; set; }
        public string WIDTH { get; set; }
        public string UNIT { get; set; }
        public string MODEL { get; set; }
        public string OP_STOCK { get; set; }
        public string OP_QTY { get; set; }
        public string CATOGORY { get; set; }
        public string SUB_CATOGORY { get; set; }
        public string ACTIVATE_STATE { get; set; }
        public string RM_COST { get; set; }
        public string noc { get; set; }
        public string vendor_code { get; set; }
        public string ex_duty { get; set; }
        public string cess_duty { get; set; }
        public string sh_duty { get; set; }
        public string cst_tax { get; set; }
        public string lst_tax { get; set; }
        public string vat { get; set; }
        public string ttcs { get; set; }
        public string surcharge { get; set; }
        public string type { get; set; }
        public string s_area { get; set; }
        public string plant { get; set; }
        public string USER_STAMP { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
        public string PLANT_ { get; set; }
        public string GATE_NO_ { get; set; }
        public string SHOP_CODE1 { get; set; }
        public string SHOP1 { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string sgst { get; set; }
        public string cgst { get; set; }
        public string igst { get; set; }
    }
}
