//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsId { get; set; }
        public string SystemName { get; set; }
        public string PrinterName { get; set; }
        public string InputPath { get; set; }
        public string OutputPath { get; set; }
        public string InvoicePath { get; set; }
        public string APIUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Flatfilepath { get; set; }
    }
}
