//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public int Id { get; set; }
        public string Product_name { get; set; }
        public string Licensed_on { get; set; }
        public string Valid_upto { get; set; }
        public string SQL { get; set; }
        public string SAP_CR { get; set; }
        public string CR_Runtime { get; set; }
        public string Adobe_DC { get; set; }
        public string PStool { get; set; }
    }
}
