//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSMData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMaster
    {
        public int Temp_ID { get; set; }
        public string Template_Name { get; set; }
        public string Inv_No_Cord { get; set; }
        public string Inv_Date_Cord { get; set; }
        public string Vendor_Cord { get; set; }
        public string Truck_No_Cord { get; set; }
        public string Client_Name_Cord { get; set; }
        public string DS_Cord { get; set; }
        public string Po_Cord { get; set; }
        public string Part_Cord { get; set; }
        public string Qty_Cord { get; set; }
        public string Rate_Cord { get; set; }
        public string Ass_Cord { get; set; }
        public string Cgst_Cord { get; set; }
        public string Sgst_Cord { get; set; }
        public string Tot_Val_Cord { get; set; }
        public string Irn_Cord { get; set; }
        public string Tcs_Cord { get; set; }
        public string Shopcd_Cord { get; set; }
        public string HSN_Cord { get; set; }
        public string Igst_Cord { get; set; }
        public string Cgstrt_Cord { get; set; }
        public string Sgstrt_Cord { get; set; }
        public string Igstrt_Cord { get; set; }
    }
}
